trigger: ["master"]
pr: ["master"]

jobs:
- template: ci/azure-rustfmt.yml

# Basic test run on all platforms
- template: ci/azure-test-stable.yml
  parameters:
    name: Linux_Stable
    displayName: Linux + Stable Rust
    vmImage: ubuntu-16.04

# - template: ci/azure-test-stable.yml
#   parameters:
#     name: MacOS_Stable
#     displayName: OS X + Stable Rust
#     vmImage: macOS-10.13
#
# - template: ci/azure-test-stable.yml
#   parameters:
#     name: Windows_Stable
#     displayName: Windows + Stable Rust
#     vmImage: vs2017-win2016

- template: ci/azure-deploy-docs.yml
