trigger: ["master"]
pr: ["master"]

jobs:
- template: ci/azure-rustfmt.yml
  parameters:
    name: rustfmt

# Basic test run on all platforms
- template: ci/azure-test-stable.yml
  parameters:
    name: Linux_Stable
    displayName: Linux + Stable Rust
    vmImage: ubuntu-16.04

- template: ci/azure-deploy-docs.yml
  parameters:
    dependsOn:
      - rustfmt
      - Linux_Stable
