jobs:
# Check formatting
- job: rustfmt
  displayName: Check rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: ci/azure-install-rust.yml
      parameters:
        platform: Linux
        # Pin the version of Rust in case rustfmt changes.
        rust_version: 1.32.0
    - bash: |
        rustup component add rustfmt
      displayName: Install rustfmt
    - bash: |
        cargo fmt --all -- --check
      displayName: Check formatting
