parameters:
  dependsOn: []

jobs:
- job: documentation
  displayName: 'Deploy API Documentation'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  pool:
    vmImage: 'Ubuntu 16.04'
  dependsOn:
    - ${{ parameters.dependsOn }}
  steps:
  - template: azure-install-rust.yml
    parameters:
      platform: ${{parameters.name}}
      rust_version: stable
  - script: |
      cargo doc --all --no-deps
      cp -R target/doc '$(Build.BinariesDirectory)'
    displayName: 'Generate Documentation'
  - script: |
      set -e

      ls -la
      git init
      git config user.name 'Deployment Bot (from Azure Pipelines)'
      git config user.email 'deploy@tower-rs.com'
      echo 'machine github.com' > ~/.netrc
      echo 'login carllerche' >> ~/.netrc
      echo 'password $(GITHUB_TOKEN)' >> ~/.netrc
      git remote add origin https://github.com/tower-rs/tower
      git branch gh-pages origin/gh-pages
      git checkout gh-pages
      git add .
      git commit -m 'Deploy Tower API documentation'
      git push origin gh-pages
    env:
      GITHUB_TOKEN: $(githubPersonalToken)
    workingDirectory: '$(Build.BinariesDirectory)'
    displayName: 'Deploy Documentation'
